package com.proxymax.ui.theme

import androidx.compose.ui.graphics.Color

// ── Light ──────────────────────────────────────────────────────────────────
val light_background        = Color(0xFFF5F5F4)
val light_surface           = Color(0xFFFFFFFF)
val light_surface_variant   = Color(0xFFF0EFED)
val light_on_background     = Color(0xFF1A1917)
val light_on_surface        = Color(0xFF1A1917)
val light_on_surface_var    = Color(0xFF6B7280)
val light_primary           = Color(0xFF1D6A5A)
val light_primary_container = Color(0xFFD1EAE4)
val light_on_primary        = Color(0xFFFFFFFF)
val light_on_primary_con    = Color(0xFF0D3D32)
val light_secondary         = Color(0xFF5A6A74)
val light_on_secondary      = Color(0xFFFFFFFF)
val light_error             = Color(0xFFC0392B)
val light_error_container   = Color(0xFFFDECEA)
val light_on_error          = Color(0xFFFFFFFF)
val light_on_error_con      = Color(0xFF7B1A12)
val light_outline           = Color(0xFFD6D3D1)
val light_outline_variant   = Color(0xFFE7E5E4)

// ── Dark ───────────────────────────────────────────────────────────────────
val dark_background         = Color(0xFF111312)
val dark_surface            = Color(0xFF1A1C1B)
val dark_surface_variant    = Color(0xFF242725)
val dark_on_background      = Color(0xFFE8E6E3)
val dark_on_surface         = Color(0xFFE8E6E3)
val dark_on_surface_var     = Color(0xFF9CA3AF)
val dark_primary            = Color(0xFF4FB89E)
val dark_primary_container  = Color(0xFF1A3D34)
val dark_on_primary         = Color(0xFF0A2A22)
val dark_on_primary_con     = Color(0xFF9FD5C8)
val dark_secondary          = Color(0xFF8FA5AE)
val dark_on_secondary       = Color(0xFF1C2F35)
val dark_error              = Color(0xFFE57373)
val dark_error_container    = Color(0xFF3B1A1A)
val dark_on_error           = Color(0xFF1A0A0A)
val dark_on_error_con       = Color(0xFFF5A5A5)
val dark_outline            = Color(0xFF2E3130)
val dark_outline_variant    = Color(0xFF252827)
